/**
 * Alerts client — generates risk alerts from current station conditions.
 *
 * WHY THIS FILE EXISTS:
 * AlertsPanel.tsx currently just displays whatever alerts array it's
 * handed as a prop (today, that's the hardcoded list in mockData.ts).
 * The goal is for alerts to eventually be generated by Person 4's risk
 * model instead of being hand-written. This file is the swap point.
 *
 * HOW IT WORKS RIGHT NOW (no ML model yet):
 * generateAlerts() tries a real backend endpoint first. If that's not
 * reachable yet (Person 1's backend not deployed, or Person 4's model
 * not wired in yet), it falls back to a simple local rule-based check
 * (e.g. "battery below X% -> high severity alert") so the UI always has
 * something sensible to show instead of breaking or going empty.
 *
 * IMPORTANT — THIS FILE DOES NOT WIRE ITSELF INTO page.tsx:
 * page.tsx is Person 1's file, and it's currently what passes alerts
 * into AlertsPanel (`<AlertsPanel alerts={stationAlerts} />`, pulling
 * stationAlerts from mockData.ts). This client is ready to be called
 * from page.tsx once someone (likely Person 1, since it's their file)
 * decides to switch that data source — I'm not editing page.tsx myself,
 * per our file-ownership rule.
 *
 * EXPECTED BACKEND CONTRACT (confirm with Person 1 + Person 4, update
 * below if it ends up different):
 *   GET {NEXT_PUBLIC_API_URL}/alerts/{stationId}
 *   response: Array<{ id: string, severity: "low"|"medium"|"high", message: string }>
 */

import type { Alert } from "@/data/mockData";
import type { StationKey } from "@/lib/simulationClient";

export interface AlertsResult {
  alerts: Alert[];
  /** True if these came from the real backend/model, false if using local fallback rules. */
  isLive: boolean;
}

interface StationConditions {
  station: StationKey;
  batteryLevel: number;
  windSpeed?: number;
  temperature?: number;
}

const API_BASE = process.env.NEXT_PUBLIC_API_URL;

/**
 * Local fallback — simple threshold rules, not a real model. Just enough
 * to keep the panel meaningful until Person 4's model is wired in.
 */
function localFallback(conditions: StationConditions): Alert[] {
  const generated: Alert[] = [];

  if (conditions.batteryLevel <= 20) {
    generated.push({
      id: `battery-${conditions.station}`,
      severity: conditions.batteryLevel <= 10 ? "high" : "medium",
      message: `Battery reserve low — ${conditions.batteryLevel}% remaining at ${conditions.station === "bharati" ? "Bharati" : "Maitri"} station`,
    });
  }

  if (conditions.windSpeed !== undefined && conditions.windSpeed >= 60) {
    generated.push({
      id: `wind-${conditions.station}`,
      severity: conditions.windSpeed >= 90 ? "high" : "medium",
      message: `High wind speed detected — ${conditions.windSpeed} km/h`,
    });
  }

  if (conditions.temperature !== undefined && conditions.temperature <= -40) {
    generated.push({
      id: `temp-${conditions.station}`,
      severity: "medium",
      message: `Extreme low temperature — ${conditions.temperature}°C`,
    });
  }

  if (generated.length === 0) {
    generated.push({
      id: `nominal-${conditions.station}`,
      severity: "low",
      message: "All systems nominal — no active risk conditions detected",
    });
  }

  return generated;
}

/**
 * Fetch/generate alerts for a station. Tries the real backend + model
 * first, falls back to local threshold rules if that's not available yet.
 */
export async function generateAlerts(
  conditions: StationConditions
): Promise<AlertsResult> {
  if (!API_BASE) {
    return { alerts: localFallback(conditions), isLive: false };
  }

  try {
    const res = await fetch(
      `${API_BASE}/alerts/${conditions.station}`,
      { signal: AbortSignal.timeout(2500) }
    );

    if (!res.ok) throw new Error(`Alerts API returned ${res.status}`);

    const data = await res.json();

    if (!Array.isArray(data)) {
      throw new Error("Alerts API response shape didn't match expected contract");
    }

    return { alerts: data as Alert[], isLive: true };
  } catch {
    return { alerts: localFallback(conditions), isLive: false };
  }
}